name: Coverage Test

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: |
          ./gradlew clean build

      - name: Configurar Diretório de Trabalho
        run: cd build/reports/jacoco/test/

      - name: Check Jacoco coverage
        run: |
            COVERAGE=$(grep -Po 'INSTRUCTION.*missed="(\d+)".*covered="(\d+)"' build/reports/jacoco/test/jacocoTestReport.xml | awk '{ total += $2 + $3 } END { print ($3 / total) * 100 }')
            if (( $(echo "$COVERAGE < 80" | bc -l) )); then
              echo "A cobertura de código é inferior a 80%. Falha nos testes."
              exit 1
            fi