name: Coverage Test

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: |
          ./gradlew clean build

      - name: Extrair Relatório Jacoco
        run: |
          mkdir -p build/reports/jacoco/test
          cp -r **/build/reports/jacoco/test/* build/reports/jacoco/test/

      - name: Verificar Cobertura de Código
        run: |
          COVERAGE=$(grep -Po '(\d+(?:\.\d+)?(?=%))' build/reports/jacoco/test/jacocoTestReport.xml)
          if (( $(echo "$COVERAGE < 80" | bc -l) )); then
            echo "A cobertura de código é inferior a 80%. Falha nos testes."
            exit 1
          fi
